---
title: "Keras"
author: "ynakahashi"
date: "2018/11/8"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# install.packages("keras")
# library(keras)
# install_keras()
library(keras)
```

### MNIST
*** Load data ***
```{r}
mnist <- dataset_mnist()
# c(c(train_data, train_labels), c(valid_data, valid_labels)) %<-% mnist
# dim(train_data)
# dim(train_labels)
# dim(valid_data)
# dim(valid_labels)
```

*** Reshape data ***
```{r}
train_images <- mnist$train$x
train_images <- array_reshape(train_images, c(60000, 28 * 28))
train_images <- train_images / 255

valid_images <- mnist$test$x
valid_images <- array_reshape(valid_images, c(10000, 28 * 28))
valid_images <- valid_images / 255

train_labels <- mnist$train$y
valid_labels <- mnist$test$y
train_labels <- to_categorical(train_labels)
valid_labels <- to_categorical(valid_labels)
```

*** Define network ***
```{r}
model <- keras_model_sequential() %>% 
   layer_dense(units = 512, activation = "relu", input_shape = c(28 * 28)) %>% 
   layer_dense(units = 10, activation = "softmax")
```

*** Compile network ***
```{r}
model %>% compile(
   optimizer = "rmsprop",
   loss = "categorical_crossentropy",
   metrics = c("accuracy")
)
```

*** Run the model ***
```{r}
model %>% fit(train_images, train_labels, epochs = 5, batch_size = 128)
```


### IMDB
*** Load data ***
```{r}
imdb <- dataset_imdb(num_words = 10000)
```

*** Reshape data ***
```{r}
c(c(train_data, train_labels), c(test_data, test_labels)) %<-% imdb
```


```{r}
vectorize_sequences <- function(sequences, dimension = 10000) {
   results <- matrix(0, nrow = length(sequences), ncol = dimension)
   for (i in 1:length(sequences)) {
      results[i, sequences[[i]]] <- 1
   }
   results
}
x_train <- vectorize_sequences(train_data)
x_test  <- vectorize_sequences(test_data)
y_train <- as.numeric(train_labels)
y_test  <- as.numeric(test_labels)

length(unique(train_data[[1]]))
sum(x_train[1, ])
```

*** Define network ***
```{r}
model <- keras_model_sequential() %>% 
   layer_dense(units = 16, activation = "relu", input_shape = c(10000)) %>% 
   layer_dense(units = 16, activation = "relu") %>% 
   layer_dense(units = 1, activation = "sigmoid")
```


*** Separate into train & valid ***
```{r}
val_indices <- 1:10000
x_val <- x_train[val_indices, ]
partial_x_train <- x_train[-val_indices, ]
y_val <- y_train[val_indices]
partial_y_train <- y_train[-val_indices]
```

*** Compile network ***
```{r}
model %>% compile(
   optimizer = "rmsprop",
   loss = "binary_crossentropy",
   metrics = c("accuracy")
)
```

```{r}
model
```


*** Run the model ***
```{r}
history <- model %>% 
   fit(partial_x_train, partial_y_train, epochs = 20, batch_size = 512,
       validation_data = list(x_val, y_val))
```

```{r}
plot(history)
```




